/* Generated by itemis CREATE code generator. */

#ifndef STATECHART_H_
#define STATECHART_H_

#ifdef __cplusplus
extern "C" { 
#endif

/*!
* Forward declaration for the Statechart state machine.
*/
typedef struct Statechart Statechart;

/*!
* Forward declaration of the data structure for the StatechartInternal interface scope.
*/
typedef struct StatechartInternal StatechartInternal;

/*!
* Forward declaration of the data structure for the StatechartIface interface scope.
*/
typedef struct StatechartIface StatechartIface;

#ifdef __cplusplus
}
#endif

#include "../src/sc_types.h"

#ifdef __cplusplus
extern "C" { 
#endif 

/*! \file
Header of the state machine 'Statechart'.
*/

/*! Define number of states in the state enum */
#define STATECHART_STATE_COUNT 6

/*! Define dimension of the state configuration vector for orthogonal states. */
#define STATECHART_MAX_ORTHOGONAL_STATES 1

/*! Define indices of states in the StateConfVector */
#define SCVI_STATECHART_MAIN_REGION_PRELAUNCH 0
#define SCVI_STATECHART_MAIN_REGION_LAUNCH 0
#define SCVI_STATECHART_MAIN_REGION_FLYING 0
#define SCVI_STATECHART_MAIN_REGION_PEAK 0
#define SCVI_STATECHART_MAIN_REGION_FINDME 0
#define SCVI_STATECHART_MAIN_REGION_DROPPING 0

/*! Enumeration of all states */ 
typedef enum
{
	Statechart_last_state,
	Statechart_main_region_Prelaunch,
	Statechart_main_region_Launch,
	Statechart_main_region_Flying,
	Statechart_main_region_Peak,
	Statechart_main_region_Findme,
	Statechart_main_region_Dropping
} StatechartStates;


/*! Type declaration of the data structure for the StatechartInternal interface scope. */
struct StatechartInternal
{
	sc_integer baudrate;
	sc_integer buzzer_pin;
};



/*! Type declaration of the data structure for the StatechartIface interface scope. */
struct StatechartIface
{
	sc_string __StatePreLaunch;
	sc_string __StateLaunch;
	sc_string __StateFlying;
	sc_string __StatePeak;
	sc_string __StateDropping;
	sc_string __StateFindme;
	sc_boolean ActivateLaunch_raised;
	sc_boolean ActivatePeak_raised;
	sc_boolean ActivateDrop_raised;
	sc_boolean FlagOff_raised;
	sc_boolean RestartSystem_raised;
	sc_boolean GroundFlag_raised;
};





typedef struct StatechartIfaceEvBuf StatechartIfaceEvBuf;
struct StatechartIfaceEvBuf {
	sc_boolean ActivateLaunch_raised;
	sc_boolean ActivatePeak_raised;
	sc_boolean ActivateDrop_raised;
	sc_boolean FlagOff_raised;
	sc_boolean RestartSystem_raised;
	sc_boolean GroundFlag_raised;
};

typedef struct StatechartEvBuf StatechartEvBuf;
struct StatechartEvBuf {
	StatechartIfaceEvBuf iface;
};


/*! 
 * Type declaration of the data structure for the Statechart state machine.
 * This data structure has to be allocated by the client code. 
 */
struct Statechart
{
	StatechartStates stateConfVector[STATECHART_MAX_ORTHOGONAL_STATES];
	StatechartInternal internal;
	StatechartIface iface;
	sc_boolean completed;
	sc_boolean doCompletion;
	StatechartEvBuf current;
	sc_boolean isExecuting;
};



/*! Initializes the Statechart state machine data structures. Must be called before first usage.*/
extern void statechart_init(Statechart* handle);


/*! Performs a 'run to completion' step. */
extern void statechart_run_cycle(Statechart* handle);

/*! Activates the state machine. */
extern void statechart_enter(Statechart* handle);

/*! Deactivates the state machine. */
extern void statechart_exit(Statechart* handle);




/*! Gets the value of the variable '__StatePreLaunch' that is defined in the default interface scope. */ 
extern sc_string statechart_get___StatePreLaunch(const Statechart* handle);
/*! Sets the value of the variable '__StatePreLaunch' that is defined in the default interface scope. */ 
extern void statechart_set___StatePreLaunch(Statechart* handle, sc_string value);
/*! Gets the value of the variable '__StateLaunch' that is defined in the default interface scope. */ 
extern sc_string statechart_get___StateLaunch(const Statechart* handle);
/*! Sets the value of the variable '__StateLaunch' that is defined in the default interface scope. */ 
extern void statechart_set___StateLaunch(Statechart* handle, sc_string value);
/*! Gets the value of the variable '__StateFlying' that is defined in the default interface scope. */ 
extern sc_string statechart_get___StateFlying(const Statechart* handle);
/*! Sets the value of the variable '__StateFlying' that is defined in the default interface scope. */ 
extern void statechart_set___StateFlying(Statechart* handle, sc_string value);
/*! Gets the value of the variable '__StatePeak' that is defined in the default interface scope. */ 
extern sc_string statechart_get___StatePeak(const Statechart* handle);
/*! Sets the value of the variable '__StatePeak' that is defined in the default interface scope. */ 
extern void statechart_set___StatePeak(Statechart* handle, sc_string value);
/*! Gets the value of the variable '__StateDropping' that is defined in the default interface scope. */ 
extern sc_string statechart_get___StateDropping(const Statechart* handle);
/*! Sets the value of the variable '__StateDropping' that is defined in the default interface scope. */ 
extern void statechart_set___StateDropping(Statechart* handle, sc_string value);
/*! Gets the value of the variable '__StateFindme' that is defined in the default interface scope. */ 
extern sc_string statechart_get___StateFindme(const Statechart* handle);
/*! Sets the value of the variable '__StateFindme' that is defined in the default interface scope. */ 
extern void statechart_set___StateFindme(Statechart* handle, sc_string value);
/*! Raises the in event 'ActivateLaunch' that is defined in the default interface scope. */ 
extern void statechart_raise_activateLaunch(Statechart* handle);
/*! Raises the in event 'ActivatePeak' that is defined in the default interface scope. */ 
extern void statechart_raise_activatePeak(Statechart* handle);
/*! Raises the in event 'ActivateDrop' that is defined in the default interface scope. */ 
extern void statechart_raise_activateDrop(Statechart* handle);
/*! Raises the in event 'FlagOff' that is defined in the default interface scope. */ 
extern void statechart_raise_flagOff(Statechart* handle);
/*! Raises the in event 'RestartSystem' that is defined in the default interface scope. */ 
extern void statechart_raise_restartSystem(Statechart* handle);
/*! Raises the in event 'GroundFlag' that is defined in the default interface scope. */ 
extern void statechart_raise_groundFlag(Statechart* handle);

/*!
 * Checks whether the state machine is active (until 2.4.1 this method was used for states).
 * A state machine is active if it was entered. It is inactive if it has not been entered at all or if it has been exited.
 */
extern sc_boolean statechart_is_active(const Statechart* handle);

/*!
 * Checks if all active states are final. 
 * If there are no active states then the state machine is considered being inactive. In this case this method returns false.
 */
extern sc_boolean statechart_is_final(const Statechart* handle);

/*! Checks if the specified state is active (until 2.4.1 the used method for states was called isActive()). */
extern sc_boolean statechart_is_state_active(const Statechart* handle, StatechartStates state);


#ifdef __cplusplus
}
#endif 

#endif /* STATECHART_H_ */
