/* Generated by itemis CREATE code generator. */

#ifndef STATECHART_REQUIRED_H_
#define STATECHART_REQUIRED_H_

#include "../src/sc_types.h"
#include "Statechart.h"

#ifdef __cplusplus
extern "C"
{
#endif 

/*! \file
This header defines prototypes for all functions that are required by the state machine implementation.

This state machine makes use of operations declared in the state machines interface or internal scopes. Thus the function prototypes:
- statechart_sm_initUart
- statechart_sm_printState
- statechart_sm_buzzerInit
- statechart_sm_buzzerFindMe
- statechart_sm_bipReady
- statechart_sm_stateBeep
- statechart_sm_enableSensors
- statechart_sm_disableSensors
are defined.

These functions will be called during a 'run to completion step' (runCycle) of the statechart. 
There are some constraints that have to be considered for the implementation of these functions:
- make sure that the execution time is as short as possible.
*/

extern void statechart_sm_initUart(const Statechart* handle, const sc_integer baudrate);
extern void statechart_sm_printState(const Statechart* handle, const sc_string state);
extern void statechart_sm_buzzerInit(const Statechart* handle, const sc_integer pin);
extern void statechart_sm_buzzerFindMe(const Statechart* handle, const sc_integer pin);
extern void statechart_sm_bipReady(const Statechart* handle, const sc_integer pin);
extern void statechart_sm_stateBeep(const Statechart* handle, const sc_integer pin, const sc_string state);
extern void statechart_sm_enableSensors(const Statechart* handle);
extern void statechart_sm_disableSensors(const Statechart* handle);




#ifdef __cplusplus
}
#endif 

#endif /* STATECHART_REQUIRED_H_ */
