/* Generated by itemis CREATE code generator. */


#include "../src/sc_types.h"

#include "Statechart.h"
#include "Statechart_required.h"

/*! \file
Implementation of the state machine 'Statechart'
*/

#ifndef SC_UNUSED
#define SC_UNUSED(P) (void)(P)
#endif

/* prototypes of all internal functions */
static void enact_main_region_Prelaunch(Statechart* handle);
static void enact_main_region_Launch(Statechart* handle);
static void enact_main_region_Flying(Statechart* handle);
static void enact_main_region_Peak(Statechart* handle);
static void enact_main_region_Findme(Statechart* handle);
static void enact_main_region_Dropping(Statechart* handle);
static void exact_main_region_Prelaunch(Statechart* handle);
static void exact_main_region_Flying(Statechart* handle);
static void exact_main_region_Dropping(Statechart* handle);
static void enseq_main_region_Prelaunch_default(Statechart* handle);
static void enseq_main_region_Peak_default(Statechart* handle);
static void enseq_main_region_default(Statechart* handle);
static void exseq_main_region_Prelaunch(Statechart* handle);
static void exseq_main_region_Launch(Statechart* handle);
static void exseq_main_region_Flying(Statechart* handle);
static void exseq_main_region_Peak(Statechart* handle);
static void exseq_main_region_Findme(Statechart* handle);
static void exseq_main_region_Dropping(Statechart* handle);
static void exseq_main_region(Statechart* handle);
static void react_main_region__entry_Default(Statechart* handle);

/*! The reactions of state Prelaunch. */
static sc_integer main_region_Prelaunch_react(Statechart* handle, const sc_integer transitioned_before);

/*! The reactions of state Launch. */
static sc_integer main_region_Launch_react(Statechart* handle, const sc_integer transitioned_before);

/*! The reactions of state Flying. */
static sc_integer main_region_Flying_react(Statechart* handle, const sc_integer transitioned_before);

/*! The reactions of state Peak. */
static sc_integer main_region_Peak_react(Statechart* handle, const sc_integer transitioned_before);

/*! The reactions of state Findme. */
static sc_integer main_region_Findme_react(Statechart* handle, const sc_integer transitioned_before);

/*! The reactions of state Dropping. */
static sc_integer main_region_Dropping_react(Statechart* handle, const sc_integer transitioned_before);


static void swap_in_events(Statechart* handle);

static void clear_current_events(Statechart* handle);

static void clear_in_events(Statechart* handle);

static void micro_step(Statechart* handle);




static void statechart_internal_set_baudrate(Statechart* handle, sc_integer value)
;
static void statechart_internal_set_buzzer_pin(Statechart* handle, sc_integer value)
;




void statechart_init(Statechart* handle)
{
	sc_integer i;
	
	for (i = 0; i < STATECHART_MAX_ORTHOGONAL_STATES; ++i)
	{
		handle->stateConfVector[i] = Statechart_last_state;
	}
	
				
	clear_in_events(handle);
	swap_in_events(handle);
	
	
	/* Default init sequence for statechart Statechart */
	statechart_internal_set_baudrate(handle, 115200);
	statechart_internal_set_buzzer_pin(handle, 18);
	statechart_set___StatePreLaunch(handle, (sc_string) "PRELAUNCH");
	statechart_set___StateLaunch(handle, (sc_string) "LAUNCH");
	statechart_set___StateFlying(handle, (sc_string) "FLYING");
	statechart_set___StatePeak(handle, (sc_string) "PEAK");
	statechart_set___StateDropping(handle, (sc_string) "DROPPING");
	statechart_set___StateFindme(handle, (sc_string) "FINDME");
	
	handle->isExecuting = bool_false;
}

void statechart_run_cycle(Statechart* handle)
{
	/* Performs a 'run to completion' step. */
	if (handle->isExecuting == bool_true)
	{ 
		return;
	} 
	handle->isExecuting = bool_true;
	swap_in_events(handle);
	handle->doCompletion = bool_false;
	do
	{ 
		if (handle->completed == bool_true)
		{ 
			handle->doCompletion = bool_true;
		} 
		handle->completed = bool_false;
		micro_step(handle);
		clear_current_events(handle);
		handle->doCompletion = bool_false;
	} while (handle->completed == bool_true);
	handle->isExecuting = bool_false;
}

void statechart_enter(Statechart* handle)
{
	/* Activates the state machine. */
	if (handle->isExecuting == bool_true)
	{ 
		return;
	} 
	handle->isExecuting = bool_true;
	/* Default enter sequence for statechart Statechart */
	enseq_main_region_default(handle);
	handle->doCompletion = bool_false;
	do
	{ 
		if (handle->completed == bool_true)
		{ 
			handle->doCompletion = bool_true;
		} 
		handle->completed = bool_false;
		micro_step(handle);
		clear_current_events(handle);
		handle->doCompletion = bool_false;
	} while (handle->completed == bool_true);
	handle->isExecuting = bool_false;
}

void statechart_exit(Statechart* handle)
{
	/* Deactivates the state machine. */
	if (handle->isExecuting == bool_true)
	{ 
		return;
	} 
	handle->isExecuting = bool_true;
	/* Default exit sequence for statechart Statechart */
	exseq_main_region(handle);
	handle->stateConfVector[0] = Statechart_last_state;
	handle->isExecuting = bool_false;
}


sc_boolean statechart_is_active(const Statechart* handle)
{
	sc_boolean result = bool_false;
	sc_integer i;
	
	for(i = 0; i < STATECHART_MAX_ORTHOGONAL_STATES; i++)
	{
		result = result || handle->stateConfVector[i] != Statechart_last_state;
	}
	
	return result;
}

/* 
 * Always returns 'false' since this state machine can never become final.
 */
sc_boolean statechart_is_final(const Statechart* handle)
{
	SC_UNUSED(handle);
	return bool_false;
}

sc_boolean statechart_is_state_active(const Statechart* handle, StatechartStates state)
{
	sc_boolean result = bool_false;
	switch (state)
	{
		case Statechart_main_region_Prelaunch :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_REGION_PRELAUNCH] == Statechart_main_region_Prelaunch
			);
				break;
		case Statechart_main_region_Launch :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_REGION_LAUNCH] == Statechart_main_region_Launch
			);
				break;
		case Statechart_main_region_Flying :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_REGION_FLYING] == Statechart_main_region_Flying
			);
				break;
		case Statechart_main_region_Peak :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_REGION_PEAK] == Statechart_main_region_Peak
			);
				break;
		case Statechart_main_region_Findme :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_REGION_FINDME] == Statechart_main_region_Findme
			);
				break;
		case Statechart_main_region_Dropping :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_REGION_DROPPING] == Statechart_main_region_Dropping
			);
				break;
			default:
				result = bool_false;
				break;
		}
		return result;
	}

static void swap_in_events(Statechart* handle)
{
	handle->current.iface.ActivateLaunch_raised = handle->iface.ActivateLaunch_raised;
	handle->iface.ActivateLaunch_raised = bool_false;
	handle->current.iface.ActivatePeak_raised = handle->iface.ActivatePeak_raised;
	handle->iface.ActivatePeak_raised = bool_false;
	handle->current.iface.ActivateDrop_raised = handle->iface.ActivateDrop_raised;
	handle->iface.ActivateDrop_raised = bool_false;
	handle->current.iface.FlagOff_raised = handle->iface.FlagOff_raised;
	handle->iface.FlagOff_raised = bool_false;
	handle->current.iface.RestartSystem_raised = handle->iface.RestartSystem_raised;
	handle->iface.RestartSystem_raised = bool_false;
	handle->current.iface.GroundFlag_raised = handle->iface.GroundFlag_raised;
	handle->iface.GroundFlag_raised = bool_false;
}

static void clear_current_events(Statechart* handle)
{
	handle->current.iface.ActivateLaunch_raised = bool_false;
	handle->current.iface.ActivatePeak_raised = bool_false;
	handle->current.iface.ActivateDrop_raised = bool_false;
	handle->current.iface.FlagOff_raised = bool_false;
	handle->current.iface.RestartSystem_raised = bool_false;
	handle->current.iface.GroundFlag_raised = bool_false;
}

static void clear_in_events(Statechart* handle)
{
	handle->iface.ActivateLaunch_raised = bool_false;
	handle->iface.ActivatePeak_raised = bool_false;
	handle->iface.ActivateDrop_raised = bool_false;
	handle->iface.FlagOff_raised = bool_false;
	handle->iface.RestartSystem_raised = bool_false;
	handle->iface.GroundFlag_raised = bool_false;
}

static void micro_step(Statechart* handle)
{
	switch(handle->stateConfVector[ 0 ])
	{
		case Statechart_main_region_Prelaunch :
		{
			main_region_Prelaunch_react(handle,-1);
			break;
		}
		case Statechart_main_region_Launch :
		{
			main_region_Launch_react(handle,-1);
			break;
		}
		case Statechart_main_region_Flying :
		{
			main_region_Flying_react(handle,-1);
			break;
		}
		case Statechart_main_region_Peak :
		{
			main_region_Peak_react(handle,-1);
			break;
		}
		case Statechart_main_region_Findme :
		{
			main_region_Findme_react(handle,-1);
			break;
		}
		case Statechart_main_region_Dropping :
		{
			main_region_Dropping_react(handle,-1);
			break;
		}
		default: 
			/* do nothing */
			break;
	}
}


void statechart_raise_activateLaunch(Statechart* handle)
{
	handle->iface.ActivateLaunch_raised = bool_true;
}

void statechart_raise_activatePeak(Statechart* handle)
{
	handle->iface.ActivatePeak_raised = bool_true;
}

void statechart_raise_activateDrop(Statechart* handle)
{
	handle->iface.ActivateDrop_raised = bool_true;
}

void statechart_raise_flagOff(Statechart* handle)
{
	handle->iface.FlagOff_raised = bool_true;
}

void statechart_raise_restartSystem(Statechart* handle)
{
	handle->iface.RestartSystem_raised = bool_true;
}

void statechart_raise_groundFlag(Statechart* handle)
{
	handle->iface.GroundFlag_raised = bool_true;
}



sc_string statechart_get___StatePreLaunch(const Statechart* handle)
{
	return handle->iface.__StatePreLaunch;
}
void statechart_set___StatePreLaunch(Statechart* handle, sc_string value)
{
	handle->iface.__StatePreLaunch = value;
}
sc_string statechart_get___StateLaunch(const Statechart* handle)
{
	return handle->iface.__StateLaunch;
}
void statechart_set___StateLaunch(Statechart* handle, sc_string value)
{
	handle->iface.__StateLaunch = value;
}
sc_string statechart_get___StateFlying(const Statechart* handle)
{
	return handle->iface.__StateFlying;
}
void statechart_set___StateFlying(Statechart* handle, sc_string value)
{
	handle->iface.__StateFlying = value;
}
sc_string statechart_get___StatePeak(const Statechart* handle)
{
	return handle->iface.__StatePeak;
}
void statechart_set___StatePeak(Statechart* handle, sc_string value)
{
	handle->iface.__StatePeak = value;
}
sc_string statechart_get___StateDropping(const Statechart* handle)
{
	return handle->iface.__StateDropping;
}
void statechart_set___StateDropping(Statechart* handle, sc_string value)
{
	handle->iface.__StateDropping = value;
}
sc_string statechart_get___StateFindme(const Statechart* handle)
{
	return handle->iface.__StateFindme;
}
void statechart_set___StateFindme(Statechart* handle, sc_string value)
{
	handle->iface.__StateFindme = value;
}

static void statechart_internal_set_baudrate(Statechart* handle, sc_integer value)
{
	handle->internal.baudrate = value;
}
static void statechart_internal_set_buzzer_pin(Statechart* handle, sc_integer value)
{
	handle->internal.buzzer_pin = value;
}


/* implementations of all internal functions */

static void enact_main_region_Prelaunch(Statechart* handle)
{
	/* Entry action for state 'Prelaunch'. */
	statechart_sm_initUart(handle,handle->internal.baudrate);
	statechart_sm_buzzerInit(handle,handle->internal.buzzer_pin);
	statechart_sm_stateBeep(handle,handle->internal.buzzer_pin, handle->iface.__StatePreLaunch);
	handle->completed = bool_true;
}

static void enact_main_region_Launch(Statechart* handle)
{
	/* Entry action for state 'Launch'. */
	statechart_sm_printState(handle,handle->iface.__StateLaunch);
	statechart_sm_stateBeep(handle,handle->internal.buzzer_pin, handle->iface.__StateLaunch);
	handle->completed = bool_true;
}

/* Entry action for state 'Flying'. */
static void enact_main_region_Flying(Statechart* handle)
{
	/* Entry action for state 'Flying'. */
	statechart_sm_enableSensors(handle);
	statechart_sm_printState(handle,handle->iface.__StateFlying);
	statechart_sm_stateBeep(handle,handle->internal.buzzer_pin, handle->iface.__StateFlying);
}

static void enact_main_region_Peak(Statechart* handle)
{
	/* Entry action for state 'Peak'. */
	statechart_sm_printState(handle,handle->iface.__StatePeak);
	statechart_sm_stateBeep(handle,handle->internal.buzzer_pin, handle->iface.__StatePeak);
	handle->completed = bool_true;
}

/* Entry action for state 'Findme'. */
static void enact_main_region_Findme(Statechart* handle)
{
	/* Entry action for state 'Findme'. */
	statechart_sm_printState(handle,handle->iface.__StateFindme);
	statechart_sm_stateBeep(handle,handle->internal.buzzer_pin, handle->iface.__StateFindme);
}

static void enact_main_region_Dropping(Statechart* handle)
{
	/* Entry action for state 'Dropping'. */
	statechart_sm_enableSensors(handle);
	statechart_sm_printState(handle,handle->iface.__StateDropping);
	statechart_sm_stateBeep(handle,handle->internal.buzzer_pin, handle->iface.__StateDropping);
	handle->completed = bool_true;
}

/* Exit action for state 'Prelaunch'. */
static void exact_main_region_Prelaunch(Statechart* handle)
{
	/* Exit action for state 'Prelaunch'. */
	statechart_sm_printState(handle,handle->iface.__StatePreLaunch);
}

/* Exit action for state 'Flying'. */
static void exact_main_region_Flying(Statechart* handle)
{
	/* Exit action for state 'Flying'. */
	statechart_sm_disableSensors(handle);
}

/* Exit action for state 'Dropping'. */
static void exact_main_region_Dropping(Statechart* handle)
{
	/* Exit action for state 'Dropping'. */
	statechart_sm_disableSensors(handle);
}

/* 'default' enter sequence for state Prelaunch */
static void enseq_main_region_Prelaunch_default(Statechart* handle)
{
	/* 'default' enter sequence for state Prelaunch */
	enact_main_region_Prelaunch(handle);
	handle->stateConfVector[0] = Statechart_main_region_Prelaunch;
}

/* 'default' enter sequence for state Peak */
static void enseq_main_region_Peak_default(Statechart* handle)
{
	/* 'default' enter sequence for state Peak */
	enact_main_region_Peak(handle);
	handle->stateConfVector[0] = Statechart_main_region_Peak;
}

/* 'default' enter sequence for region main region */
static void enseq_main_region_default(Statechart* handle)
{
	/* 'default' enter sequence for region main region */
	react_main_region__entry_Default(handle);
}

/* Default exit sequence for state Prelaunch */
static void exseq_main_region_Prelaunch(Statechart* handle)
{
	/* Default exit sequence for state Prelaunch */
	handle->stateConfVector[0] = Statechart_last_state;
	exact_main_region_Prelaunch(handle);
}

/* Default exit sequence for state Launch */
static void exseq_main_region_Launch(Statechart* handle)
{
	/* Default exit sequence for state Launch */
	handle->stateConfVector[0] = Statechart_last_state;
}

/* Default exit sequence for state Flying */
static void exseq_main_region_Flying(Statechart* handle)
{
	/* Default exit sequence for state Flying */
	handle->stateConfVector[0] = Statechart_last_state;
	exact_main_region_Flying(handle);
}

/* Default exit sequence for state Peak */
static void exseq_main_region_Peak(Statechart* handle)
{
	/* Default exit sequence for state Peak */
	handle->stateConfVector[0] = Statechart_last_state;
}

/* Default exit sequence for state Findme */
static void exseq_main_region_Findme(Statechart* handle)
{
	/* Default exit sequence for state Findme */
	handle->stateConfVector[0] = Statechart_last_state;
}

/* Default exit sequence for state Dropping */
static void exseq_main_region_Dropping(Statechart* handle)
{
	/* Default exit sequence for state Dropping */
	handle->stateConfVector[0] = Statechart_last_state;
	exact_main_region_Dropping(handle);
}

/* Default exit sequence for region main region */
static void exseq_main_region(Statechart* handle)
{
	/* Default exit sequence for region main region */
	/* Handle exit of all possible states (of Statechart.main_region) at position 0... */
	switch(handle->stateConfVector[ 0 ])
	{
		case Statechart_main_region_Prelaunch :
		{
			exseq_main_region_Prelaunch(handle);
			break;
		}
		case Statechart_main_region_Launch :
		{
			exseq_main_region_Launch(handle);
			break;
		}
		case Statechart_main_region_Flying :
		{
			exseq_main_region_Flying(handle);
			break;
		}
		case Statechart_main_region_Peak :
		{
			exseq_main_region_Peak(handle);
			break;
		}
		case Statechart_main_region_Findme :
		{
			exseq_main_region_Findme(handle);
			break;
		}
		case Statechart_main_region_Dropping :
		{
			exseq_main_region_Dropping(handle);
			break;
		}
		default: 
			/* do nothing */
			break;
	}
}

/* Default react sequence for initial entry  */
static void react_main_region__entry_Default(Statechart* handle)
{
	/* Default react sequence for initial entry  */
	enseq_main_region_Prelaunch_default(handle);
}


static sc_integer main_region_Prelaunch_react(Statechart* handle, const sc_integer transitioned_before)
{
	/* The reactions of state Prelaunch. */
 			sc_integer transitioned_after = transitioned_before;
	if (handle->doCompletion == bool_true)
	{ 
		/* Default exit sequence for state Prelaunch */
		handle->stateConfVector[0] = Statechart_last_state;
		exact_main_region_Prelaunch(handle);
		/* 'default' enter sequence for state Launch */
		enact_main_region_Launch(handle);
		handle->stateConfVector[0] = Statechart_main_region_Launch;
	}  else
	{
		/* Always execute local reactions. */
		transitioned_after = transitioned_before;
	}
	return transitioned_after;
}

static sc_integer main_region_Launch_react(Statechart* handle, const sc_integer transitioned_before)
{
	/* The reactions of state Launch. */
 			sc_integer transitioned_after = transitioned_before;
	if (handle->doCompletion == bool_true)
	{ 
		/* Default exit sequence for state Launch */
		handle->stateConfVector[0] = Statechart_last_state;
		/* 'default' enter sequence for state Flying */
		enact_main_region_Flying(handle);
		handle->stateConfVector[0] = Statechart_main_region_Flying;
	}  else
	{
		/* Always execute local reactions. */
		transitioned_after = transitioned_before;
	}
	return transitioned_after;
}

static sc_integer main_region_Flying_react(Statechart* handle, const sc_integer transitioned_before)
{
	/* The reactions of state Flying. */
 			sc_integer transitioned_after = transitioned_before;
	if (handle->doCompletion == bool_false)
	{ 
		if ((transitioned_after) < (0))
		{ 
			if (handle->current.iface.ActivatePeak_raised == bool_true)
			{ 
				exseq_main_region_Flying(handle);
				enseq_main_region_Peak_default(handle);
				transitioned_after = 0;
			} 
		} 
		/* If no transition was taken */
		if ((transitioned_after) == (transitioned_before))
		{ 
			/* then execute local reactions. */
			transitioned_after = transitioned_before;
		} 
	} return transitioned_after;
}

static sc_integer main_region_Peak_react(Statechart* handle, const sc_integer transitioned_before)
{
	/* The reactions of state Peak. */
 			sc_integer transitioned_after = transitioned_before;
	if (handle->doCompletion == bool_true)
	{ 
		/* Default exit sequence for state Peak */
		handle->stateConfVector[0] = Statechart_last_state;
		/* 'default' enter sequence for state Dropping */
		enact_main_region_Dropping(handle);
		handle->stateConfVector[0] = Statechart_main_region_Dropping;
	}  else
	{
		/* Always execute local reactions. */
		transitioned_after = transitioned_before;
	}
	return transitioned_after;
}

static sc_integer main_region_Findme_react(Statechart* handle, const sc_integer transitioned_before)
{
	/* The reactions of state Findme. */
 			sc_integer transitioned_after = transitioned_before;
	if (handle->doCompletion == bool_false)
	{ 
		if ((transitioned_after) < (0))
		{ 
			if (handle->current.iface.RestartSystem_raised == bool_true)
			{ 
				exseq_main_region_Findme(handle);
				enseq_main_region_Prelaunch_default(handle);
				transitioned_after = 0;
			} 
		} 
		/* If no transition was taken */
		if ((transitioned_after) == (transitioned_before))
		{ 
			/* then execute local reactions. */
			transitioned_after = transitioned_before;
		} 
	} return transitioned_after;
}

static sc_integer main_region_Dropping_react(Statechart* handle, const sc_integer transitioned_before)
{
	/* The reactions of state Dropping. */
 			sc_integer transitioned_after = transitioned_before;
	if (handle->doCompletion == bool_true)
	{ 
		/* Default exit sequence for state Dropping */
		handle->stateConfVector[0] = Statechart_last_state;
		exact_main_region_Dropping(handle);
		/* 'default' enter sequence for state Findme */
		enact_main_region_Findme(handle);
		handle->stateConfVector[0] = Statechart_main_region_Findme;
	}  else
	{
		/* Always execute local reactions. */
		transitioned_after = transitioned_before;
	}
	return transitioned_after;
}




